# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GithubRunner < Formula
  desc "Self-hosted GitHub Actions runner"
  homepage "https://github.com/nficano/github-runner"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nficano/github-runner/releases/download/v0.1.3/github-runner_0.1.3_darwin_amd64.zip"
      sha256 "4fcca2885d6696cb687595ee4d8d55d779ecb047b2edcc64d7cebbb790c28511"

      define_method(:install) do
        bin.install "github-runner"
        etc.install "configs/config.example.toml" => "github-runner/config.toml"
        (var/"github-runner").mkpath
        (var/"log").mkpath
        bash_completion.install "scripts/completions/github-runner.bash" => "github-runner"
        zsh_completion.install "scripts/completions/github-runner.zsh" => "_github-runner"
        fish_completion.install "scripts/completions/github-runner.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nficano/github-runner/releases/download/v0.1.3/github-runner_0.1.3_darwin_arm64.zip"
      sha256 "66d822393779e82e6ce4f8f084d55ce4920f13878f2337bb0849cfb60b246c46"

      define_method(:install) do
        bin.install "github-runner"
        etc.install "configs/config.example.toml" => "github-runner/config.toml"
        (var/"github-runner").mkpath
        (var/"log").mkpath
        bash_completion.install "scripts/completions/github-runner.bash" => "github-runner"
        zsh_completion.install "scripts/completions/github-runner.zsh" => "_github-runner"
        fish_completion.install "scripts/completions/github-runner.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nficano/github-runner/releases/download/v0.1.3/github-runner_0.1.3_linux_amd64.tar.gz"
      sha256 "55e9a5bbb00124e3d27acc995505693a08f4c7fd4d15bd07384a13c2a72b806c"
      define_method(:install) do
        bin.install "github-runner"
        etc.install "configs/config.example.toml" => "github-runner/config.toml"
        (var/"github-runner").mkpath
        (var/"log").mkpath
        bash_completion.install "scripts/completions/github-runner.bash" => "github-runner"
        zsh_completion.install "scripts/completions/github-runner.zsh" => "_github-runner"
        fish_completion.install "scripts/completions/github-runner.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nficano/github-runner/releases/download/v0.1.3/github-runner_0.1.3_linux_arm64.tar.gz"
      sha256 "66536592dfa4281987febe055bce2341f073dfef6f2a373a66cb4eb182172d73"
      define_method(:install) do
        bin.install "github-runner"
        etc.install "configs/config.example.toml" => "github-runner/config.toml"
        (var/"github-runner").mkpath
        (var/"log").mkpath
        bash_completion.install "scripts/completions/github-runner.bash" => "github-runner"
        zsh_completion.install "scripts/completions/github-runner.zsh" => "_github-runner"
        fish_completion.install "scripts/completions/github-runner.fish"
      end
    end
  end

  service do
    run [opt_bin/"github-runner", "start", "--config", etc/"github-runner/config.toml"]
    keep_alive true
    log_path var/"log/github-runner.log"
    error_log_path var/"log/github-runner.log"
    working_dir var/"github-runner"
  end

  test do
    system "#{bin}/github-runner", "version"
  end
end
